"""empty message

Revision ID: 52553c8e9a48
Revises: f3fc1ade42a4
Create Date: 2023-06-08 21:06:16.041830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52553c8e9a48'
down_revision = 'f3fc1ade42a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('color_eyes')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('color_eyes', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
