"""empty message

Revision ID: f3fc1ade42a4
Revises: dc5908bb42ab
Create Date: 2023-06-06 18:11:56.394849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fc1ade42a4'
down_revision = 'dc5908bb42ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_eyes', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('characters_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('characters_email_key', ['email'])
        batch_op.drop_column('color_eyes')

    # ### end Alembic commands ###
